/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApiErrorFeedback: typeof import('./src/components/common/ApiErrorFeedback.vue')['default']
    BaseCard: typeof import('./src/components/common/BaseCard.vue')['default']
    DragDropContainer: typeof import('./src/components/common/DragDropContainer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    EnhancedButton: typeof import('./src/components/common/EnhancedButton.vue')['default']
    EnhancedForm: typeof import('./src/components/common/EnhancedForm.vue')['default']
    EnhancedFormItem: typeof import('./src/components/common/EnhancedFormItem.vue')['default']
    EnhancedSelect: typeof import('./src/components/common/EnhancedSelect.vue')['default']
    ErrorBoundary: typeof import('./src/components/common/ErrorBoundary.vue')['default']
    ErrorReport: typeof import('./src/components/common/ErrorReport.vue')['default']
    ErrorReportManager: typeof import('./src/components/common/ErrorReportManager.vue')['default']
    ErrorState: typeof import('./src/components/common/ErrorState.vue')['default']
    ErrorTester: typeof import('./src/components/common/ErrorTester.vue')['default']
    GlobalErrorDisplay: typeof import('./src/components/common/GlobalErrorDisplay.vue')['default']
    HeadManager: typeof import('./src/components/common/HeadManager.vue')['default']
    ListContainer: typeof import('./src/components/common/ListContainer.vue')['default']
    LoadingIndicator: typeof import('./src/components/common/LoadingIndicator.vue')['default']
    OptimizedTable: typeof import('./src/components/common/OptimizedTable.vue')['default']
    PageTransition: typeof import('./src/components/common/PageTransition.vue')['default']
    PreloadManager: typeof import('./src/components/common/PreloadManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StoreManager: typeof import('./src/components/common/StoreManager.vue')['default']
    UserFeedback: typeof import('./src/components/common/UserFeedback.vue')['default']
    VirtualScroller: typeof import('./src/components/common/VirtualScroller.vue')['default']
  }
}
